services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-7860}:${PORT:-7860}"  #  Use environment variable, fallback to 7860
    environment:
      PORT: "${PORT:-7860}"  #  Set the PORT environment variable inside the container
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              count: all
